services:
  telegram_meme:
    container_name: telegram_auto_poster
    build:
      context: .
      dockerfile: Dockerfile
    # image: python:3.12-slim
    restart: no
    networks:
      - proxy
      - teleg_net
    volumes:
      - ./telegram_auto_poster:/workspace/telegram_auto_poster
      - ./pyproject.toml:/workspace/pyproject.toml
      - ./uv.lock:/workspace/uv.lock
      - ./videos:/workspace/videos
      - ./photos:/workspace/photos
      - ./config.ini:/workspace/config.ini
      - ./ooodnakov.session:/workspace/ooodnakov.session
      - ./wm.png:/workspace/wm.png
      # - ./ooodnakov.session-journal:/workspace/ooodnakov.session-journal
      # - ./data:/app/data
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  proxy:
    external: true
    name: proxy
  teleg_net:
    external: true
    driver: bridge

volumes:
  minio_data:
    driver: local

