services:
  telegram_meme:
    container_name: telegram_auto_poster
    # image: python:3.12-slim
    restart: always
    networks:
      - proxy
    volumes:
      - ./:/app
      # - ./data:/app/data
    build: .
    # start bash and run the script
    command: ["bash", "/app/run_bg.sh"]
    environment:
      - TZ=Europe/Moscow

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
networks:
  proxy:
    external: true
    name: proxy
