services:
  telegram_meme:
    container_name: telegram_auto_poster
    build:
      context: .
      dockerfile: Dockerfile
    # image: python:3.12-slim
    restart: no
    networks:
      - proxy
      - teleg_net
    volumes:
      - ./telegram_auto_poster:/workspace/telegram_auto_poster
      - ./pyproject.toml:/workspace/pyproject.toml
      - ./uv.lock:/workspace/uv.lock
      - ./videos:/workspace/videos
      - ./photos:/workspace/photos
      - ./config.ini:/workspace/config.ini
      - ./ooodnakov.session:/workspace/ooodnakov.session
      - ./wm.png:/workspace/wm.png
      # - ./ooodnakov.session-journal:/workspace/ooodnakov.session-journal
      # - ./data:/app/data
    environment:
      - TZ=Europe/Moscow
      - MINIO_HOST=minio
      - MINIO_PORT=8999
      - MINIO_ACCESS_KEY=super_secret_name
      - MINIO_SECRET_KEY=super_secret_key
      - VALKEY_HOST=valkey_common
      - VALKEY_PORT=6379
      - VALKEY_PASS=redis
      - REDIS_PREFIX=telegram_auto_poster
      # Mysql/Maria connection parameters:
      - DB_MYSQL_HOST=telegram_db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=tma
      - DB_MYSQL_PASSWORD=tma
      - DB_MYSQL_NAME=tma
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  db:
    container_name: telegram_db
    image: 'mariadb:latest'
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=tma
      - MARIADB_DATABASE=tma
      - MARIADB_USER=tma
      - MARIADB_PASSWORD=tma
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - teleg_net

networks:
  proxy:
    external: true
    name: proxy
  teleg_net:
    external: true
    driver: bridge

volumes:
  minio_data:
    driver: local

