name: Respond to Code Review Submission

# This workflow triggers only when a PR review is submitted.
on:
  pull_request_review:
    types: [submitted]

jobs:
  post-fix-comment:
    # This job runs if the review body contains "Code Review".
    if: contains(github.event.review.body, 'Code Review')
    runs-on: ubuntu-latest
    permissions:
      # The action needs permission to write comments on pull requests.
      pull-requests: write
    steps:
      - name: Post "fix it" comment
        uses: mshick/add-pr-comment@v2
        with:
          message: "@codex fix mentioned problems in this pr"
          # Use the unique ID of the review to ensure a new comment is posted
          # for each matching review, preventing the action from updating its old posts.
          message-id: "codex-fix-review-${{ github.event.review.id }}"
