name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache uv packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Garage
        run: |
          cargo install garage --locked

      - name: Install PogoCache
        run: |
          POGO_VERSION="1.3.0"
          mkdir -p "$HOME/.cargo/bin"
          curl -L "https://github.com/tidwall/pogocache/releases/download/${POGO_VERSION}/pogocache-linux-amd64.tar.gz" \
            -o /tmp/pogocache.tar.gz
          tar -xzf /tmp/pogocache.tar.gz -C /tmp
          install -m 0755 /tmp/pogocache-linux-amd64/pogocache "$HOME/.cargo/bin/pogocache"

      - name: Set up dependencies
        run: |
          uv sync --dev

      - name: Run ruff format check
        run: uv run ruff format --check

      - name: Run ruff lint
        run: uv run ruff check --diff

      - name: Run tests with coverage
        run: |
          export VALKEY_BACKEND=pogocache
          export VALKEY_SERVER_PATH="$HOME/.cargo/bin/pogocache"
          uv run pytest -n auto --cov --cov-report=html

      - name: Upload HTML coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
